// <auto-generated />
using System;
using AgencyOnboarding.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgencyOnboarding.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318162717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgencyOnboarding.API.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandColor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<int>("OnboardingSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledCallAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingSessionId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.ContractSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OnboardingSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SignatureDataUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingSessionId")
                        .IsUnique();

                    b.ToTable("ContractSignatures");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.IntakeForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OnboardingSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingSessionId")
                        .IsUnique();

                    b.ToTable("IntakeForms");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.OnboardingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("OnboardingSessions");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("OnboardingSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingSessionId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("ContractText")
                        .HasColumnType("text");

                    b.Property<string>("IntakeFormConfigJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequireBooking")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireContract")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireFileUpload")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireIntake")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequirePayment")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OnboardingSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingSessionId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Booking", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.OnboardingSession", "Session")
                        .WithOne("Booking")
                        .HasForeignKey("AgencyOnboarding.API.Models.Booking", "OnboardingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.ContractSignature", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.OnboardingSession", "Session")
                        .WithOne("ContractSignature")
                        .HasForeignKey("AgencyOnboarding.API.Models.ContractSignature", "OnboardingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.IntakeForm", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.OnboardingSession", "Session")
                        .WithOne("IntakeForm")
                        .HasForeignKey("AgencyOnboarding.API.Models.IntakeForm", "OnboardingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.OnboardingSession", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.Agency", "Agency")
                        .WithMany("Sessions")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyOnboarding.API.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Payment", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.OnboardingSession", "Session")
                        .WithOne("Payment")
                        .HasForeignKey("AgencyOnboarding.API.Models.Payment", "OnboardingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Template", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.Agency", "Agency")
                        .WithMany("Templates")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.UploadedFile", b =>
                {
                    b.HasOne("AgencyOnboarding.API.Models.OnboardingSession", "Session")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("OnboardingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.Agency", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("AgencyOnboarding.API.Models.OnboardingSession", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("ContractSignature");

                    b.Navigation("IntakeForm");

                    b.Navigation("Payment");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
